core/urls.py
from django.urls import path 
from . import views
app_name = 'main'


urlpatterns = [
    path('' , views.home , name="home"),
    path('jobs/' , views.job_page , name="job_page"),
    path('contact/' , views.contact , name="contact"),
    path('login/' , views.login_page , name="login"),
    path('register/' , views.register_page , name="register"),
    path('logout_page/' , views.logout_page , name="logout"),
    path('add_job/' , views.add_job , name="add_job"),
    path('profile_page/' , views.profile_page , name="profile"),
    path('jon_detail/<slug:slug>' , views.job_detail , name="job_detail")
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
TYPES = (
    ('f' , 'full-time'),
    ('p' , 'part-time'),
)
class Job(models.Model):
    user = models.ForeignKey(User , related_name="owner_job", on_delete=models.CASCADE , blank=True , null=True)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='jobs/')
    job_type = models.CharField(choices=TYPES , max_length=200)
    descrption = models.TextField(max_length=400)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField()
    salary = models.IntegerField()
    location = models.CharField(max_length=200)
    experiance = models.IntegerField()
    slug = models.SlugField(max_length=200 , blank=True , null=True)
    
    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title



class Contact(models.Model):
    message = models.TextField(max_length=300)
    phone_number = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = ('contact')
        verbose_name_plural = ('contacts')
    
    def __str__(self):
        return self.name
    



class ApplForJob(models.Model):
    name = models.CharField(max_length=50)
    email =  models.EmailField(max_length=254)
    website = models.URLField(max_length = 200 , blank=True , null=True)
    cv = models.FileField(upload_to='cvs', max_length = 100, blank=True , null=True)
    cover = models.TextField(max_length=260, blank=True , null=True)

    def __str__(self):
        return str(self.name)
    

core/forms.py
from django import forms 
from .models import ApplForJob , Job , Contact
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact 
        fields = '__all__'



class AddJob(forms.ModelForm):
    class Meta:
        model = Job 
        fields = ['title' , 'image' , 'job_type' , 'descrption' , 'vacancy' , 'salary' , 'location' , 'experiance']




class ApplyJob(forms.ModelForm):
    class Meta:
        model = ApplForJob
        fields = '__all__'



class LoginForm(forms.ModelForm):
    username = forms.CharField(label='Enter the username')
    password = forms.CharField(label='Enter the password' , widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username' , 'password']



class RegisterForm(UserCreationForm):
    username = forms.CharField(label='username')
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label='password' , widget=forms.PasswordInput())
    password2 = forms.CharField(label='check the password password' , widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username' , 'email' , 'password1', 'password2']

core/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse 
from django.http import HttpResponseRedirect
from .models import Job
from .forms import ApplyJob , AddJob , ContactForm , LoginForm , RegisterForm
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.models import User
from .filters import JobFilter
# Create your views here.

def home(request):
    jobs = Job.objects.all()
    counter = jobs.count()
    return render(request , 'core/index.html' , {
        'jobs':jobs , 'counter':counter 
    })


def job_detail(request , slug):
    job_details = Job.objects.get(slug=slug)
    if request.method == "POST":
        form = ApplyJob(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            print('save')
            #add link to refresh page
            return HttpResponseRedirect(reverse('main:job_page'))
    else:
        form = ApplyJob()
    return render(request , 'core/job_details.html' , {
        'form':form , 'job_detail':job_details
    })



def add_job(request):
    if request.method == 'POST':
        form = AddJob(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:home'))
        else:
            return HttpResponseRedirect(reverse('main:add_job'))
    else:
        print('Error')
        form = AddJob()
    return render(request , 'core/add_job.html' , {
        'form':form
    })


def job_page(request):
    jobs = Job.objects.all()
    counter = Job.objects.count()
    myFilter = JobFilter(request.GET , queryset= jobs)
    jobs = myFilter.qs
    return render(request , 'core/jobs.html' , {
        'jobs':jobs , 'counter':counter ,"myFilter":myFilter
    })







def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
    else:
        contact_form = ContactForm()
    return render(request , 'core/contact.html' , {
        'form':contact_form
    })



def login_page(request):
    if request.user.is_authenticated:
       return HttpResponseRedirect(reverse('main:home'))
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request ,username=username , password=password)
            if user is not None:
                login(request , user)
                return HttpResponseRedirect(reverse('main:home'))    
        else:
            form = LoginForm()
    return render(request , 'core/login.html' , {
        'form':form
    })


def register_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('main:home'))    
    else:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('main:login'))
        else:
            form = RegisterForm()
    return render(request , 'core/register.html' , {
        'form':form
    })


def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:home'))



def profile_page(request):
    return render(request , 'core/profile.html' , {
        
    })

core/templates/core/add_job.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

<section style="margin-top:100px;" class="job_details_area">
    <div class="container">
        <div class="row">
            <h1 style="padding:10px;">add new Job</h1>
            <form  method="POST">
                {% csrf_token %} {% bootstrap_form form %}
                <input class="btn btn-primary" type="submit" value="submit" />
            </form>
        </div>
    </div>
</section>

{% endblock %}

core/templates/core/contact.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>contact</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
  <!-- ================ contact section start ================= -->
  <section class="contact-section section_padding">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <div id="map" style="height: 480px;"></div>
        <script>
          function initMap() {
            var uluru = {lat: -25.363, lng: 131.044};
            var grayStyles = [
              {
                featureType: "all",
                stylers: [
                  { saturation: -90 },
                  { lightness: 50 }
                ]
              },
              {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -31.197, lng: 150.744},
              zoom: 9,
              styles: grayStyles,
              scrollwheel:  false
            });
          }
          
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
        
      </div>


      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form"  method="post" id="contactForm" novalidate="novalidate">
            {% csrf_token %} {% bootstrap_form form %}
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->
   
  {% endblock %}

core/templates/core/jobs.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{ counter }}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form  method="get">
                                {% csrf_token %} {% bootstrap_form myFilter.form %}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% if  job.image.url %}
                                            <img style="width: 6vw; height:10vh;"  src="{{ job.image.url }}" alt="">
                                            {% endif %}
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'main:job_detail' job.slug %}"><h4> {{ job.title }} </h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.location}} </p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}} </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'main:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.published_at}} </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        <li><a href="#"> <i class="ti-angle-left"></i> </a></li>
                                        <li><a href="#"><span>01</span></a></li>
                                        <li><a href="#"><span>02</span></a></li>
                                        <li><a href="#"> <i class="ti-angle-right"></i> </a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock %}

core/templates/core/login.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}


<div style="margin-top:100px;" class="job_details_area">
    <div class="container">
        <div class="row">
            <h1  style="padding:10px;">sign in</h1>
            <form method="POST">
                {% csrf_token %} {% bootstrap_form form %}
                <input type="submit" value="submit" />
            </form>
        </div>
    </div>
</div>

{% endblock  %}

core/templates/core/profile.html
{% extends 'layout.html' %}
{% load static  %}
{% block content %}


<div style="margin-top:100px;" class="job_details_area">
    <div class="container">
        <h1>Personal information</h1>
       
            <h1> username : {{ request.user.username }}</h1>
            <h2> email : {{ request.user.email }} </h2>
    </div>
</div>
   
{% endblock %}

core/templates/core/register.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div style="margin-top:100px;" class="job_details_area">
    <div class="container">
        <div class="row">
            <h1  style="padding:10px;">create new Account </h1>
            <form method="POST">
                {% csrf_token %} {% bootstrap_form form %}
                <input type="submit" value="submit" />
            </form>
        </div>
    </div>
</div>

{% endblock  %}

templates/layout.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static  'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static  'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static  'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static  'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static  'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static  'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static  'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="/">
                                        <img src="{% static 'img/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">home</a></li>
                                            <li><a href="{% url 'main:job_page' %}">Browse Job</a></li>
                                            <li><a href="{% url 'main:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'main:profile' %}">{{request.user.username  }}</a>
                                        </div>
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'main:logout' %}">logout</a>
                                        </div>
                                        <div class="d-none d-lg-block">
                                            <a class="boxed-btn3" href="{% url 'main:add_job' %}">Post a Job</a>
                                        </div>
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'main:login' %}">Log in</a>
                                        </div>
                                        <div class="d-none d-lg-block">
                                            <a class="boxed-btn3" href="{% url 'main:register' %}"> signup</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->



    {% block content %}
{% endblock  %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static  'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static  'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static  'js/popper.min.js' %}"></script>
    <script src="{% static  'js/bootstrap.min.js' %}"></script>
    <script src="{% static  'js/owl.carousel.min.js' %}"></script>
    <script src="{% static  'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static  'js/ajax-form.js' %}"></script>
    <script src="{% static  'js/waypoints.min.js' %}"></script>
    <script src="{% static  'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static  'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static  'js/scrollIt.js' %}"></script>
    <script src="{% static  'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static  'js/wow.min.js' %}"></script>
    <script src="{% static  'js/nice-select.min.js' %}"></script>
    <script src="{% static  'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static  'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static  'js/plugins.js' %}"></script>
    <!-- <script src="{% static  'js/gijgo.min.js"></script> -->
    <script src="{% static  'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static  'js/contact.js' %}"></script>
    <script src="{% static  'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static  'js/jquery.form.js' %}"></script>
    <script src="{% static  'js/jquery.validate.min.js' %}"></script>
    <script src="{% static  'js/mail-script.js' %}"></script>


    <script src="{% static  'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>